# This file was generated by GoReleaser. DO NOT EDIT.
cask "repo-lister" do
  name "repo-lister"
  desc "Container image management tool using Kubernetes credentials"
  homepage "https://github.com/btwseeu78/repo-lister"
  version "0.0.4-gamma"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repo-lister"

  on_macos do
    on_intel do
      url "https://github.com/btwseeu78/repo-lister/releases/download/v#{version}/repo-lister_#{version}_darwin_x86_64.tar.gz"
      sha256 "bfa87905bb968c2115310f254cfb215954e5fbab4fe28896edd3eace68ea942a"
    end
    on_arm do
      url "https://github.com/btwseeu78/repo-lister/releases/download/v#{version}/repo-lister_#{version}_darwin_arm64.tar.gz"
      sha256 "e2f136871a721ce317402935bae8dc32100179ca1a8682e09b53fcfa16bbcdf8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/btwseeu78/repo-lister/releases/download/v#{version}/repo-lister_#{version}_linux_x86_64.tar.gz"
      sha256 "7021980ae055613ce7e0cf6288a8ad039c6afa149c041fbef8b92594844f27fe"
    end
    on_arm do
      url "https://github.com/btwseeu78/repo-lister/releases/download/v#{version}/repo-lister_#{version}_linux_arm64.tar.gz"
      sha256 "0efb2c437a617ab96fd16f6750b29dcc05497a0e8e0e8dc4e0c245d954058395"
    end
  end

  # No zap stanza required
end
