# This file was generated by GoReleaser. DO NOT EDIT.
cask "repo-lister" do
  name "repo-lister"
  desc "Container image management tool using Kubernetes credentials"
  homepage "https://github.com/btwseeu78/repo-lister"
  version "0.0.5-beta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repo-lister"

  on_macos do
    on_intel do
      url "https://github.com/btwseeu78/repo-lister/releases/download/v#{version}/repo-lister_#{version}_darwin_x86_64.tar.gz"
      sha256 "a05d6aead9efd8f8c6fc07945e4c16ac6d912d0e889f39e7e88555a42c9044f8"
    end
    on_arm do
      url "https://github.com/btwseeu78/repo-lister/releases/download/v#{version}/repo-lister_#{version}_darwin_arm64.tar.gz"
      sha256 "c7b1fe958aa7ffd71ea2e0958811efa92d90b4e0c94ad5f7b4c5eb2bb3306796"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/btwseeu78/repo-lister/releases/download/v#{version}/repo-lister_#{version}_linux_x86_64.tar.gz"
      sha256 "651ea6d7be9f243ddcbee5f29f7f5e27582e552f3a988c6d5df00eca5728ea9c"
    end
    on_arm do
      url "https://github.com/btwseeu78/repo-lister/releases/download/v#{version}/repo-lister_#{version}_linux_arm64.tar.gz"
      sha256 "b88a54d641e00ef3985898b706397c04b9dcab61e716450b312edecd40c4a3fc"
    end
  end

  # No zap stanza required
end
