# This file was generated by GoReleaser. DO NOT EDIT.
cask "repo-lister" do
  name "repo-lister"
  desc "Container image management tool using Kubernetes credentials"
  homepage "https://github.com/btwseeu78/repo-lister"
  version "0.0.4-alpha"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repo-lister"

  on_macos do
    on_intel do
      url "https://github.com/btwseeu78/repo-lister/releases/download/v#{version}/repo-lister_#{version}_darwin_x86_64.tar.gz"
      sha256 "2f9b78e80778b9897d7ccd64d6403170caff9a30837052815eeb99f0a3b6c479"
    end
    on_arm do
      url "https://github.com/btwseeu78/repo-lister/releases/download/v#{version}/repo-lister_#{version}_darwin_arm64.tar.gz"
      sha256 "fc65c07e3a7c82e5f05af0a08b4377bed28d386d4f8b8c247e402dedd88cb367"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/btwseeu78/repo-lister/releases/download/v#{version}/repo-lister_#{version}_linux_x86_64.tar.gz"
      sha256 "33f2534c2791c56651ac898289249cfb0855492d6c5b36ed58e78fe5749c3a49"
    end
    on_arm do
      url "https://github.com/btwseeu78/repo-lister/releases/download/v#{version}/repo-lister_#{version}_linux_arm64.tar.gz"
      sha256 "b1dc53d2798b5c63dfd85ae794cfc76079ca1691229fdad34c95d375ffe4451e"
    end
  end

  # No zap stanza required
end
